# Generated by Django 5.1 on 2024-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eircode', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateTimeField()),
                ('temperature_2m', models.FloatField(blank=True, null=True)),
                ('relative_humidity_2m', models.FloatField(blank=True, null=True)),
                ('dew_point_2m', models.FloatField(blank=True, null=True)),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('wind_direction_10m', models.FloatField(blank=True, null=True)),
                ('wind_gusts_10m', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
